/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as erc20MintSol from "./ERC20mint.sol";
export type { erc20MintSol };
import type * as nftDutchAuctionErc20BidsSol from "./NFTDutchAuction_ERC20Bids.sol";
export type { nftDutchAuctionErc20BidsSol };
export type { MintContract } from "./MintContract";
