/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IERC20Mint } from "./IERC20Mint";
export type { IMintContract } from "./IMintContract";
export type { NFTDutchAuction_ERC20Bids } from "./NFTDutchAuction_ERC20Bids";
